Repository Velocimeter/frontend, pull requests merged in 2023-04, with the labels that each got.

#34 dont show killed gauges except if user has balance in it or votes for it
  Frontend-v1-Original/components/ssLiquidityPairs/ssLiquidityPairsTable.tsx
  Frontend-v1-Original/components/ssVotes/ssVotes.tsx
Labels: enhancement

#24 Introduce viem public client for blockchain reading
  Frontend-v1-Original/components/ssBribeCreate/ssBribeCreate.tsx
  Frontend-v1-Original/components/ssLiquidityManage/ssLiquidityManage.tsx
  Frontend-v1-Original/components/ssLiquidityPairs/ssLiquidityPairsTable.tsx
  Frontend-v1-Original/components/ssRewards/ssRewardsTable.tsx
  Frontend-v1-Original/components/ssSwap/setup.tsx
  Frontend-v1-Original/components/ssVotes/ssVotesTable.tsx
  Frontend-v1-Original/package.json
  Frontend-v1-Original/pages/api/canto/circulating-supply.ts
  Frontend-v1-Original/stores/abis/abis.ts
  Frontend-v1-Original/stores/abis/bribeABI.js
  Frontend-v1-Original/stores/abis/bribeABI.ts
  Frontend-v1-Original/stores/abis/erc20ABI.ts
  Frontend-v1-Original/stores/abis/factoryABI.ts
  Frontend-v1-Original/stores/abis/flowConvertorABI.ts
  Frontend-v1-Original/stores/abis/gaugeABI.ts
  Frontend-v1-Original/stores/abis/minterABI.ts
  Frontend-v1-Original/stores/abis/package.json
  Frontend-v1-Original/stores/abis/pairABI.ts
  Frontend-v1-Original/stores/abis/routerABI.ts
  Frontend-v1-Original/stores/abis/tokenABI.js
  Frontend-v1-Original/stores/abis/tokenABI.ts
  Frontend-v1-Original/stores/abis/veDistABI.ts
  Frontend-v1-Original/stores/abis/veTokenABI.ts
  Frontend-v1-Original/stores/abis/voterABI.ts
  Frontend-v1-Original/stores/abis/wethABI.ts
  Frontend-v1-Original/stores/accountStore.ts
  Frontend-v1-Original/stores/connectors/package.json
  Frontend-v1-Original/stores/connectors/viem.ts
  Frontend-v1-Original/stores/constants/constants.ts
  Frontend-v1-Original/stores/constants/contracts.ts
  Frontend-v1-Original/stores/constants/contractsCanto.ts
  Frontend-v1-Original/stores/constants/contractsCantoTestnet.js
  Frontend-v1-Original/stores/constants/contractsGoerli.ts
  Frontend-v1-Original/stores/helperStore.ts
  Frontend-v1-Original/stores/stableSwapStore.ts
  Frontend-v1-Original/stores/types/types.ts
  Frontend-v1-Original/yarn.lock
Labels: enhancement

#32 optimize UI styles
  Frontend-v1-Original/components/ssLiquidityManage/ssLiquidityManage.tsx
  Frontend-v1-Original/components/ssSwap/setup.tsx
  Frontend-v1-Original/components/ssSwap/ssSwap.tsx
  Frontend-v1-Original/tailwind.config.js
Labels: community suggested

#30 tvl in liq pairs table
  Frontend-v1-Original/components/ssLiquidityPairs/ssLiquidityPairsTable.tsx
Labels: enhancement

#36 Various UI Fixes + Improvements
  Frontend-v1-Original/README.md
  Frontend-v1-Original/components/layout/layout.tsx
  Frontend-v1-Original/components/ssBribeCreate/ssBribeCreate.tsx
  Frontend-v1-Original/components/ssLiquidityManage/ssLiquidityManage.tsx
  Frontend-v1-Original/components/ssLiquidityPairs/ssLiquidityPairsTable.tsx
  Frontend-v1-Original/components/ssSwap/setup.tsx
  Frontend-v1-Original/components/ssVotes/ssVotes.tsx
  Frontend-v1-Original/legacy/components/ssBribeTable/ssBribesTable.tsx
  Frontend-v1-Original/legacy/components/ssLiquidityCreate/ssLiquidityCreate.js
  Frontend-v1-Original/mainnet-canto-token-list.json
  Frontend-v1-Original/pages/home/index.tsx
Labels: enhancement, community suggested

#52 Multicall assets balances
  Frontend-v1-Original/stores/stableSwapStore.ts
Labels: enhancement

#54 Improve table sorting + minor adjustments
  Frontend-v1-Original/components/ssBribeCreate/ssBribeCreate.tsx
  Frontend-v1-Original/components/ssBribes/ssBribes.tsx
  Frontend-v1-Original/components/ssLiquidityPairs/ssLiquidityPairsTable.tsx
  Frontend-v1-Original/components/ssRewards/ssRewards.module.css
  Frontend-v1-Original/components/ssRewards/ssRewards.tsx
  Frontend-v1-Original/components/ssRewards/ssRewardsTable.tsx
  Frontend-v1-Original/components/ssVotes/ssVotes.tsx
  Frontend-v1-Original/components/ssVotes/ssVotesTable.tsx
Labels: enhancement, community suggested

#49 add UI for nft merging
  Frontend-v1-Original/components/ssRewards/ssRewards.tsx
  Frontend-v1-Original/components/ssVest/MergeNFT.tsx
  Frontend-v1-Original/components/ssVest/existingLock.tsx
  Frontend-v1-Original/components/ssVest/lock.tsx
  Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
  Frontend-v1-Original/components/ssVotes/ssVotes.tsx
  Frontend-v1-Original/components/ssVotes/ssVotesTable.tsx
  Frontend-v1-Original/hooks/useAccount.ts
  Frontend-v1-Original/package.json
  Frontend-v1-Original/pages/vest/[id]/merge.tsx
  Frontend-v1-Original/stores/constants/actions.ts
  Frontend-v1-Original/stores/stableSwapStore.ts
  Frontend-v1-Original/stores/types/types.ts
  Frontend-v1-Original/theme/dark.ts
Labels: enhancement

#67 Hotfix/two rows of bribes
  Frontend-v1-Original/components/ssRewards/ssRewards.tsx
  Frontend-v1-Original/stores/stableSwapStore.ts
Labels: bug
